### ISSUE TITLE
Error - No configuration found - Exiting

### ISSUE THREAD

**Issue by oliroe** [Roxedus/docker-containers#2]
Not sure whether it's something I'm doing or because I'm doing it on a Synology NAS but I can't get this to start. I'm using the same setup as Radarr/Sonarr/Lidarr

![image](https://user-images.githubusercontent.com/4500141/54072597-c9281e80-4274-11e9-8607-f7e5e215b425.png)

![image](https://user-images.githubusercontent.com/4500141/54072612-e826b080-4274-11e9-8331-1fcdb617417f.png)

![image](https://user-images.githubusercontent.com/4500141/54072654-d2fe5180-4275-11e9-8aa6-a02b15e1fc77.png)

**Comment by Roxedus** [comment]
Container is working. Now do the configuration like described in the [repo](https://github.com/RhinoRhys/radarr-collections/tree/master#setting-up-the-configuration-file).
Copy the default to rcm.conf.

**Comment by oliroe** [comment]
Hi. Not the case, for anyone looking for a solution please go to https://www.reddit.com/r/radarr/comments/axhllg/major_update_radarr_collections_and_people_manager/?utm_medium=android_app&utm_source=share
