### ISSUE TITLE
So close to working....

### ISSUE THREAD

**Issue by BinsonBuzz** [Roxedus/docker-containers#3]
Hi

Great work turning this into a docker.  I'm probably doing something stupid - can you help please. I've added the docker (to Unraid) using:

`docker run -d --name='radarr-collections' --net='br0.55' --ip='192.168.50.10' --log-opt max-size='50m' --log-opt max-file='3' -e TZ="Europe/London" -e HOST_OS="Unraid" -e 'args'='-f' -e 'PGID'='100' -e 'PUID'='99' -v '/mnt/user/appdata/other/plex/radarr-collections-master/config/':'/config':'rw' 'si0972/radarr-collections'  `

But it just does this in my logs:

```
Traceback (most recent call last):
File "/app/rcm.py", line 416, in <module>
data = api("Radarr")
File "/app/rcm.py", line 159, in api
return response.json() ## EXIT
File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 897, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python2.7/json/decoder.py", line 382, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

So close... please help.

Thanks in advance

**Comment by Roxedus** [comment]
Are you running radarr Aphrodite?

**Comment by BinsonBuzz** [comment]
Hi thanks for getting back to me so quickly.  Yes, I'm using v3.  I just did a quick install of Radarr v2 and it worked.

Is it not compatible with Radarr v3?

**Comment by Roxedus** [comment]
The app havent had an update after radarr v2 was a thing

**Comment by BinsonBuzz** [comment]
Thanks

**Comment by BinsonBuzz** [comment]
Closing - as usual it was me being stupid - working now
