### ISSUE TITLE
Docker stopped working

### ISSUE THREAD

**Issue by BinsonBuzz** [Roxedus/docker-containers#4]
Hi

This used to work perfectly for me, but I'm getting this error now:

```
Traceback (most recent call last):
File "/app/rcm.py", line 418, in <module>
for movie in data:
TypeError: 'int' object is not iterable
Traceback (most recent call last):
File "/app/rcm.py", line 418, in <module>
for movie in data:
TypeError: 'int' object is not iterable
```
I'm using unRAID and here's my settings:

`root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='radarr-collections' --net='br0' --ip='192.168.1.90' --cpuset-cpus='2,3,4,8,9,13,18,19,20,24,25,29' -e TZ="Europe/London" -e HOST_OS="Unraid" -e 'args'='-f' -e 'PGID'='100' -e 'PUID'='99' -v '/mnt/user/appdata/other/plex/radarr-collections-master/config/':'/config':'rw' 'si0972/radarr-collections'`

Thanks in advance for any help

**Comment by Roxedus** [comment]
The upstream api probably broke. this does not look like a container issue

**Comment by BinsonBuzz** [comment]
I found this in the discord:

https://discordapp.com/channels/552909534398775306/553022462829395988/865779017583427585

```
I can't guarantee anything but if you add v3 into line 414 so it says this instead

 radarr_url += u"{0}/api/v3/movie" 

It might work again....
```
Which worked for another user - is this something you can fix, or does the master script need updating as you link to it?

Thanks

**Comment by Roxedus** [comment]
It has to be updated upstream.

**Comment by BinsonBuzz** [comment]
ok - thanks
