### ISSUE TITLE
Error - {}/rcm.conf does not exist.

### ISSUE THREAD

**Issue by pcooney4** [Roxedus/docker-containers#6]
Running with Args -c -f
Config path is correct for the volume
Getting the following:

```
Traceback (most recent call last):

  File "/app/rcm.py", line 300, in <module>

    if not Path.exists(Path.joinpath(config_path, "rcm.conf")): nologfatal(u"\n" + "Error - {}/rcm.conf does not exist.".format(config_path))

  File "/usr/local/lib/python3.9/pathlib.py", line 972, in joinpath

    return self._make_child(args)

AttributeError: 'str' object has no attribute '_make_child'

```
![Screen Shot 2021-11-15 at 9 56 39 AM](https://user-images.githubusercontent.com/38225199/141803376-2f061f69-6704-4a4b-a000-b8d0e7d1ed46.png)

file exists

![Screen Shot 2021-11-15 at 9 57 45 AM](https://user-images.githubusercontent.com/38225199/141803634-5472959e-8f9d-4aaf-b35c-35abac87e62d.png)

**Comment by fabsau** [comment]
I have the same issue.

**Comment by pcooney4** [comment]
This has been fixed..
https://github.com/RhinoRhys/radarr-collections/commit/85a970862baa2df89794982b1c0a83f58d8f8776

Can we get a new build pls?

**Comment by Roxedus** [comment]
Built.
